

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG


spring:
#  cloud:
#    gateway:
#      routes:
#        - id: app-1
#          uri: https://httpbin.org/get
#          predicates:
#          - Path=/get
  data:
    mongodb:
      uri: mongodb://localhost:27017/gateway
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway
